### ISSUE TITLE
[bug] [`v2.0.0-beta.8`] packages without exports are flagged as missing dependencies

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1014]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

Sage 10 build process with `bud` should run without hanging/freezing.

### Actual Behavior

Sage 10 build process with `bud` hangs/freezes unexpectedly and has to be manually cancelled (e.g. using `Ctrl`+`c`, twice btw.).

### Steps To Reproduce

1. Create an empty Sage 10 project from `main` branch (`composer create-project roots/sage sage10 dev-main`).
2. Ensure all dependencies are installed (`npm install`; `composer install`).
3. Run the build (`yarn build`), note that the build runs fine.
4. Add the `npm` package [`box-sizing-border-box`](https://www.npmjs.com/package/box-sizing-border-box) (`yarn add box-sizing-border-box`) (for replicating this bug, it doesn't matter whether it is a `development` dependency or not).
For replicating this bug, there is no need for an `import` or similar reference, the package just has to be installed.
5. Run the build again (`yarn build`). Note that the build now hangs/freezes indefinitely and has to be terminated manually.
Running the build with the `--no-dashboard` flag (just learned about it from this bug report form), 
the build doesn't hang but fails with an error (see the `Logs` section below).
6. As additional proof that it is indeed this package that causes this bug, uninstall/remove that package again (`yarn remove box-sizing-border-box`).
7. Re-run the build a third time, note that the build now run completes normally again.

Note: Why this particular package [`box-sizing-border-box`](https://www.npmjs.com/package/box-sizing-border-box) is "cryptonite" to the build runner is a mystery to me. I also manually stripped fields and files from that installed package, but this doesn't help.
Maybe some metadata about this package when it is installed that causes issues with the build process?
There may be other packages that are similar structured and would also cause this issue.

The issue occurred the first time with the latest Sage 10 release `v2.0.0-beta.8`, 
but hadn't happen before as with `v2.0.0-beta.7`.

### version

`@roots/bud/5.1.0 wsl-x64 node-v16.9.1` (`./node_modules/.bin/bud --version`)

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

### Logs

```shell
[compiler] › ✖  ModuleNotFoundError: Module not found: Error: Can't resolve '@wordpress/blocks' in '[secure]/resources/scripts' 
    at [secure]/node_modules/webpack/lib/Compilation.js:2011:28
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create ([secure]/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create ([secure]/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at [secure]/node_modules/webpack/lib/NormalModuleFactory.js:972:5
```

### Configuration

```shell
No configuration changes. The newly created Sage 10 theme is used as-is.
```

### Relevant .budfiles

No changes to the `.budfile`s. The newly created Sage 10 theme is used as-is.

**Comment by kellymears** [comment]
This is because that module can't be imported. I get that it doesn't need to be imported (had never heard of [linkedin/eyeglass](https://github.com/linkedin/eyeglass) before!) but [Bud.Project](https://budjs.netlify.app/api/interfaces/project) wants to resolve it as part of its module resolution strategy. Having not found anything it bails on the entire idea of extensions and drops an error in the log about its plans. The culprit is the [hasMissingDependencies](https://budjs.netlify.app/api/interfaces/peers#hasMissingDependencies) call in [Bud.Peers](https://budjs.netlify.app/api/interfaces/peers)

This shouldn't be a problem in whatever release #1005 ends up in. 

If you exported a stub module (cjs) in that package, it wouldn't break.

## Note about scss imports

Anticipating a potential follow-up issue:

- If you try to import the css from it, that would be fine.
- If you try to import the scss in it, that would break it.

SCSS transpilation will only be run on assets found in bud's src directory (`./resources` for sage). this is a pretty big win for performance since we don't need to go trawling through all the scss assets people left around in `node_modules`. the overwhelming majority of projects won't import them. 

You can modify what you want to include/exclude from different transpilers with the rules api. I tried to make it easier than dealing with loaders and ruleset items because I anticipated this edge case:

You can specify what you want to try to import from with any of the records in `build.rules`:
```ts
// you can do it with a callback (it is passed the `Bud` object at build time)
app.build.rules.css.setInclude(({path}) => path('project'))
// or by directly setting it 
app.build.rules.css.setInclude(app.path('project'))
```

You can specify based on exclusions in a similar way:
```ts
app.build.rules.css.setExclude(({path}) => path('project', 'node_modules'))
// or
app.build.rules.css.setExclude(app.path('project'))
```

If you want to see the final object bud will pass to webpack you can call `make` on it:
```ts
app.dump(app.build.rules.css.make())
```

Beta docs for interfaces mentioned above:

- [Rule.Interface['setInclude']](https://budjs.netlify.app/api/interfaces/rule.interface#setInclude) - set inclusions for a rule
- [Rule.Interface['setExclude']](https://budjs.netlify.app/api/interfaces/rule.interface#setExclude) - set exclusions for a rule

**Comment by strarsis** [comment]
@kellymears: Interesting! I don't use `eyeglass` anymore by the way since webpack and loaders finally got decent enough support for importing modules directly. This is an extra feature for that module from a time where `eyeglass` was more popular and the only robust method for importing SASS related stylesheets and functions.
There are also other packages that have `eyeglass` support, so those packages may also cause a build hanging/error.

This worked in `beta.7` before updating to `beta.8`:
```scss
@import "~box-sizing-border-box/index";
````

**Comment by kellymears** [comment]
i'm not sure exactly what the execution order is i don't think that it's ever even getting to that call. if it is, it doesn't matter, the build is still going to get wrecked.

i think this is why:

1. it tries to import your package but can't find the exports or default export.
2. bud.project.peers throws out a red flag that there is an unresolvable module. 
3. no extensions boot. if they did, the run might end early enough that the user can't even run `yarn bud install` to acquire whatever is missing. so, the safest thing in `bud v5.1.0` is to catch the exception, log it, and let the runtime continue.
4. since no extensions are called, [@roots/sage](https://www.npmjs.com/package/@roots/sage) never runs or registers any of _its_ dependencies. and so, [@roots/bud-wordpress-externals](https://www.npmjs.com/package/@roots/bud-wordpress-externals) never runs (it maps `@wordpress` namespace packages to the `wp` window variable). 
5. `webpack` tries to actually import `@wordpress/blocks`. It isn't in `node_modules`. 💀

#1005 bud won't try to import your package because dependencies are fully managed.

I would still consider providing default exports for CJS and ESM in `box-sizing-border-box`. [Publish ESM and CJS in a single package](https://antfu.me/posts/publish-esm-and-cjs)

**Comment by strarsis** [comment]
@kellymears: Thanks for the breakdown! I will add this to the package.
Though it would be still good if `bud` becomes more resilient against those kinds of packages.

**Comment by strarsis** [comment]
@kellymears: Alright, little follow-up here: I finally added the package `exports` (release `v1.2.0`):
https://www.npmjs.com/package/box-sizing-border-box/v/1.2.0
It seems to fix the issue in my setup - if I haven't applied unnoticed extra workarounds/modifications of course.

However, after adding the `export` the classical, external SCSS import doesn't work anymore:
```scss
@import "~box-sizing-border-box/index.scss";
````

Edit: The error message still showed old SCSS, so I found out that `bud` has a cache that can be manually cleaned:
`yarn run bud clean`

I tried other `@import` approaches, like `@import "box-sizing-border-box";` and `@import "@box-sizing-border-box";` but those don't work either, currently the `index.scss` inside the `box-sizing-border-box` package can't be found.

Edit 2: I got it working, but it isn't pretty:
```scss
@import "../../node_modules/box-sizing-border-box/index";
````
I hope I can return to the `~` or `@` path prefix.
