### ISSUE TITLE
Feature Request: Add support for Vue Versions

### ISSUE THREAD

**Issue by kupoback** [roots/bud#1024]
Looking to work with this, however, since Vue 3 is not officially replacing Vue 2 as of now, Vue 2 is still being used in projects. Would love it if we could specify which version of Vue to use when @roots/bud-vue is used.

**Comment by kellymears** [comment]
I'm not a vue user so I don't think I have the bandwidth to support both versions. But I'm leaving this open because I would like it if we did. 

@QWp6t that said, you're the only vue user I know.. if you provided me with a boilerplate webpack config to replicate I think we might be able to do it? I don't know what it takes. 

vue 3 was already kind of a pain to deal with because I don't know enough about the framework.

**Comment by kupoback** [comment]
Is there any update on this? Going to be using Sage 10 soon, and would love to leverage this extension.

**Comment by kellymears** [comment]
I am pretty confident that #1328 is going to open the door for this. 

Steps to do this in a bud project:

Add the set of dependencies that are required for vue 2 to the project manifest:

https://github.com/roots/bud/blob/61db831a9e361497cc36e024bee7a9eedd7c278c/examples/vue-legacy/package.json#L20-L25

Write code:

https://github.com/roots/bud/blob/61db831a9e361497cc36e024bee7a9eedd7c278c/examples/vue-legacy/src/index.js#L1-L21

Let me know if anything looks funky in that code -- as it serves as the integration tests for vue 2 compat.

**Comment by kellymears** [comment]
This is supported in 5.8.0. See the [`examples dir`](https://github.com/roots/bud/tree/main/examples) for a working implementation to reference.
