### ISSUE TITLE
[bug] `bud dev` constantly re-rendered dashboard output causes flickering + high CPU usage in VS Code

### ISSUE THREAD

**Issue by farmerpaul** [roots/bud#1094]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

When running `bud dev` for development from a VS Code integrated terminal, I would expect the dashboard output to remain essentially static _unless_ it's compiling source code. Although I don't mind an animated unicode spinner, I would expect such a spinner to be the only character that is re-rendered in the console output, at a low framerate. I would expect that running `bud dev` in the background not to cause my MBP to consume unwarranted CPU cycles, and certainly not so many CPU cycles that it causes the fan to run.

### Actual Behavior

When running `bud dev` for development from a VS Code integrated terminal, the dashboard output appears to be getting fully re-rendered/redrawn, even when there are no code changes underway (I'm guessing this is related to the animated spinner ⠿). Consequently, the output continuously flickers and incurs higher than needed CPU usage, partly due to a related code rendering process required by VS Code for integrated terminals. On my MBP, running `bud dev` consumes enough CPU cycles (at least ~75%) that it results in continuous operation of the laptop fan, which is rare for me. No past webpack-based build system I've used has had this effect.

Here is a demonstration of the flickering:
![flickery](https://user-images.githubusercontent.com/1282772/152375026-5cfb6735-d5dc-4766-a66e-6abef88454ca.gif)

Here is an example screengrab of Activity Monitor listing three process that are associated with the extra rendering produced by the terminal output:
<img width="324" alt="Screen Shot 2022-02-03 at 11 22 24 AM" src="https://user-images.githubusercontent.com/1282772/152375191-517e68e5-f078-45c2-baf2-a4dbcf51617b.png">

When I stop `bud dev`, in addition to the `node` process ending (which is the process spawned by `bud dev`), and Code Helper and Window Server processes return to their typical, low CPU usage.

This problem also seems to cause unnecessary constant data transfer when running `bud dev` in a remote VS Code session, which I do on the regular.

**Question:** I understand that the `--no-dashboard` option is available to turn off the dashboard altogether, which does work around this issue, however I rely on the dashboard output for compilation status. Is there an option to just turn off the animated spinner, if that's in fact the culprit?

### Steps To Reproduce

1. Open an integrated terminal in VS Code on a MacBook Pro.
1. Run `bud dev` from a Bud-based project root.
1. Watch for flickering console output and higher than normal CPU usage in Activity Monitor.

### version

@roots/bud/5.2.0 darwin-x64 node-v16.13.2

### What package manager are you using?

yarn classic

### version

1.22.5

### Are you using pnpm?

- [ ] yes
- [X] no

### Configuration

```shell
/**
 * @typedef {import('@roots/bud').Bud} Bud
 *
 * @param {Bud} app
 */

module.exports = (app) =>
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['scripts/app.js', 'styles/app.css'],
      editor: ['scripts/editor.js', 'styles/editor.css'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets([app.path('src', 'images')])

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch([
      'tailwind.config.js',
      'resources/views/**/*.blade.php',
      'app/View/**/*.php',
    ])

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('https://silverstone.test')

    /**
     * Public path of application assets
     */
    .setPublicPath('/app/themes/sage/public/');
```

### Relevant .budfiles

I can provide these if requested; it will take time for me to redact sensitive information.

**Comment by QWp6t** [comment]
@kellymears I think this might be related to line wrapping.

**Comment by kellymears** [comment]
i dont think it is the spinner. 

I think the re-rendering in this case is because the height of the displayed content exceeds the height of the terminal viewport.

Ink and its box model just don't do do well with that. To be honest, its worse in iterm visually (but doesn't cause the same cpu hit).

ink wants to render any time text is going to flow outside of the viewport. with a lot of interfaces that would mean the user is resizing the window (its pretty cool that you can do a 12 column grid in the terminal). but in this case it causes the jittering and constant rerendering -- ink will obviously never get it to all fit but it doesnt ever quit.

I'm actually working on a PR to render everything using the Ink static component -- which I noticed gatsby using in their cli. Not sure if yarn is still using it, but they leaned on Static as well. 

it behaves much more like a standard terminal app, but still allows for the loading bar to appear below the stream without it affecting readability of logs or requiring clearing the console -- which is the most important thing.

for now use --no-dashboard to disable ink entirely and --log to enable webpack reporting.

**Comment by kellymears** [comment]
this'll be included in the next release 👍🏽
