### ISSUE TITLE
[Feature request] Open browser with `bud` server

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1148]
It would be handy if the browser can be automatically opened with the URL to the `bud` server proxy URL.
It should be quite easy to implement using the [`open`](https://www.npmjs.com/package/open) (formerly `opn`) package.
BrowserSync did this, too.

**Comment by kellymears** [comment]
I think we'll start with fixing the notifier because it includes a link to open the dev site, and once that handle is fixed it should be easy to implement this package.

I discovered last night that oclif cli's error handler doesn't emit to `stdout` or `stderr` streams and also doesn't allow the error to fall through.

Easy to remove, thankfully. So, I should have a better sense of why notifier is failing when our error handler can actually report on it:

https://github.com/roots/bud/blob/d0e32cad4460623a6da0a72b624ab99ef8d574d2/sources/%40roots/bud-framework/src/Framework/framework.process.ts#L3-L60

https://github.com/roots/bud/blob/d0e32cad4460623a6da0a72b624ab99ef8d574d2/sources/%40roots/bud/bin/bud.js#L5

**Comment by kellymears** [comment]
this is part of 5.8.0 🎉
