### ISSUE TITLE
Bug: Wordpress external dependencies overwrites React -> HMR Not working

### ISSUE THREAD

**Issue by filipac** [roots/bud#1181]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Seems that `@roots/wordpress-externals-webpack-plugin` registers `react` and `react-dom` as external dependencies thus  in entrypoints.js the `dependencies` array includes those 2 scripts.
This is ok on production mode, but when having React in development mode with HMR on, it overwrites the react-dom and react package needed for HMR to work thus hot reloading is not working.

#### What have you tried?
Comment out `react` and `react-dom` from `node_modules/@roots/wordpress-dependencies-webpack-plugin/lib/cjs/index.js` and `node_modules/@roots/wordpress-externals-webpack-plugin/lib/cjs/index.js`.

#### What insights have you gained?
When you comment out those two packages from the files mentioned above, hot reloading in React works again and the bundle no longer uses the production React js from the WordPress directory.

#### Possible solutions
Treat `react` and `react-dom` as external scripts only in production mode. Or maybe allow an option to not treat those 2 as external dependencies.

#### Temporary workarounds
Comment out `react` and `react-dom` from `node_modules/@roots/wordpress-dependencies-webpack-plugin/lib/cjs/index.js` and `node_modules/@roots/wordpress-externals-webpack-plugin/lib/cjs/index.js`.

### Steps To Reproduce

1. Install `@roots/bud-react` and setup a sample React component + render it in page
2. Run `yarn dev`
3. Change something in the React component and note that HMR is not working
4. Stop `yarn dev` and comment out `react` and `react-dom` from `node_modules/@roots/wordpress-dependencies-webpack-plugin/lib/cjs/index.js` and `node_modules/@roots/wordpress-externals-webpack-plugin/lib/cjs/index.js`.
5. Run `yarn dev` again and notice that now HMR works as expected.

### Expected Behavior

Hot module replacement should work in React when running `yarn dev`

### Actual Behavior

HMR is not working because the `react` and `react-dom` is treated as external script and loaded from wp core JS files, which is React in Production Mode and missing tweaks for HMR.

### Versions

10

**Comment by kellymears** [comment]
@filipac this makes sense to me. It's a worthwhile change for the improved debugging, all else notwithstanding.

A better workaround might be to remove the externals plugin in development from the `bud.config.js` file itself:

```ts
   app.when(app.isDevelopment, () => {
      app.extensions.remove('@roots/bud-wordpress-externals-webpack-plugin');
    })
```

Again, I think this is a worthwhile thing to do in development regardless (for non-minified error reporting, at minimum). But, I seem to have functional hot reloading with this app code:

```ts
// resources/scripts/app.js
import {domReady} from '@roots/sage/client';
import React from 'react';
import {render} from 'react-dom';

import {Component} from './component';

const init = () => {
  render(<Component />, document.querySelector('#app'));
};

domReady(init);
import.meta.webpackHot?.accept(init);
```

```ts
// resources/scripts/component.js
import React from 'react';

export const Component = () => {
  return (
    <div>
      <h1>Component!</h1>
    </div>
  );
};
```

Curious what might be causing HMR to not work for you, outright.

**Comment by flmuel** [comment]
Hi @kellymears!
Maybe not quite right here, HMR is working for me, but I also had to remove the wordpress externals extension from dev build:
```js
app.extensions.remove('@roots/wordpress-externals-webpack-plugin')
```

I use Sage/WordPress together with React components (load bud-react accordingly). As mentioned by @filipac, the packages which are registered as externals cause the problem. I was often annoyed about the fact that no dev suitable errors are logged. Now I know what the problem was :)

It took me several hours to figure out why [@react-pdf/renderer](https://github.com/diegomura/react-pdf) is not working. In the dev build it always came to a freeze (100% CPU usage) due to an error with react-reconciler, which was already described some years ago in the following issue: https://github.com/diegomura/react-pdf/issues/336

So just want to inform, that there are still cases, where wordpress externals breaks the dev build.
**But also a question**: Do you know what effects the removal of this package has? I noticed that the endpoint prefix wp-json is now missing when running apiFetch. And if you could point me to another solution than setting it like so:
```js
wp.apiFetch.use(wp.apiFetch.createRootURLMiddleware('/wp-json/'))
```
I'd appreciate it!

_
developing with bud 5.7.6

**Comment by flmuel** [comment]
Unfortunately, removing the package also causes the rebuild to take an extremely long time.

**Comment by kellymears** [comment]
In 5.8.0, this extension key changed. To do the same thing in versions >= 5.8.0:

```ts
app.extensions.remove('@roots/bud-wordpress-externals')
```

Or, accomplished with a little less force:

```ts
app.extensions.get('@roots/bud-wordpress-externals').disable()
```

Ref: https://github.com/roots/bud/pull/1328

**Comment by kellymears** [comment]
@flmuel you might consider upgrading from 5.7.6. v6.3.3 is a very solid release. 

As for what these extensions do:

- `@roots/bud-wordpress-externals` is a simple adapter for `@roots/wordpress-externals-webpack-plugin`. They are separate so that `@roots/wordpress-externals-webpack-plugin` can be used with webpack directly.
- `'@roots/wordpress-externals-webpack-plugin'` uses the webpack ExternalsPlugin API to replace certain import statements with `window.wp` references. It replaces:
  - _most_ `@wordpress/*` packages
  - jquery
  - lodash
  - react
  - react-dom 
- Removing `@roots/bud-wordpress-externals` will prevent `@roots/wordpress-externals-webpack-plugin` from being utilized as a webpack plugin. This will cause those packages to be bundled with your application.
- I am fairly confident in how this works because I wrote them.

I'm not sure how the wordpress api package works. By disabling the externals extension you are now using the bundled code and not the `window.wp.api` var; if `window.wp.api` comes preconfigured you that likely doesn't apply to the instance you are bundling.

Personally, I just make an api module and import it where needed:

```ts
import axios, { AxiosInstance } from "axios";

export const api: AxiosInstance = axios.create({
  baseURL: app.config.baseUrl,
  headers: {
    "content-type": "application/json",
    "X-WP-Nonce": app.config.nonce,
  },
});

export const fetcher = (url) =>
  api.request({ url }).then((res) => {
    return res.data;
  });
```

You could also try setting up your own external for just this one package:

```ts
export default async (bud) => {
  bud.externals({
    "@wordpress/api-fetch": "window.wp.api",
  });
  // ...config
});
```

Lastly, it makes sense that your bundle time goes up, as you are now bundling react, react-dom, and whatever `@wordpress/*` dependencies. `@wordpress/block-editor` is a huge package: https://bundlephobia.com/package/@wordpress/editor@12.12.0. So is `@wordpress/block-library`: https://bundlephobia.com/package/@wordpress/block-library@7.10.0. Just as a couple examples.

**Comment by flmuel** [comment]
@kellymears Thank you for all your input.
I have found the best solution to my problem. WordPress loads the scripts for Dev appropriately if you add "define('SCRIPT_DEBUG', true);" to wp-config.php.
So much better than always building these dependencies for your bundle.

**Comment by kellymears** [comment]
I'm glad you're sorted and doubly glad there is a WordPress way of handling this. I'm going to mark this issue as closed. 🥳
