### ISSUE TITLE
[bug] HTTPS is no longer working

### ISSUE THREAD

**Issue by retlehs** [roots/bud#1320]
SSL during dev is not working after #1319. 

if this is just a configuration issue, i'm still worried about how this previously worked with less configuration prior to #1319.

another tag/release can't be made until instructions are more clear on how to get SSL working prior to #1319. 

## configurations that previously worked

```js
    .proxy('https://example.test')
    .serve('https://localhost:3000');
```

```js
    .proxy('https://example.test');
```

## attempts at getting configuration working

(these don't work)

```js
    .proxy('https://example.test')
    .serve({ssl: true});
```

```js
    .serve({
      host: 'https://localhost',
      port: 3000,
    })
```

```js
    .serve({
      ssl: true,
      host: 'https://localhost',
      port: 3000,
    })
```

```
  # ZERO CONFIG / no .proxy or .serve
  (dev loads on non https)
```

**Comment by aksld** [comment]
I can confirm this bug.
Still working with bud 5.7.3

**Comment by kellymears** [comment]
SSL works.

If you aren't actually configuring node to serve over https because you have a certificate trusted by your system, you shouldn't specify `https:` protocol. 

Trellis example:

```ts
bud.serve('http://0.0.0.0')
```

The site will remain accessible via https on the host computer even though node is serving over http. 

This is also what's included in sage v10.1.6, which @retlehs tagged yesterday following a conversation he and I had about this confusion. See:

https://github.com/roots/sage/blob/82ad056fae9af21004cc711fa79d3826c61d93c3/bud.config.js#L36-L40

If you actually need to configure SSL (which is most people who are serving from their host computer directly), you'll need to pass the key and cert.

Example for valet:

```ts
bud.serve({
  host: "example.test",
  cert: app.path("@certs/example.test.crt"),
  key: app.path("@certs/example.test.key"),
});
```

I just ran this locally and it definitely works.

**Comment by retlehs** [comment]
@aksld this issue was created in-between releases yesterday and should not be an issue with any version of bud that's in the wild

can you please make a topic on our discourse if you still need help?

**Comment by aksld** [comment]
Sorry !

Maybe it's a my fault but before I was using (not working with last version) :

```
bud.serve('https://my-site.com', {
  key: '/path/to/site.key',
  cert: '/path/to/site.crt',
})
```

And now, If i'm following @kellymears instructions (working with last version) :

```
bud.serve({
  host: "example.test",
  key: '/path/to/site.key',
  cert: '/path/to/site.crt',
});
```

**Comment by retlehs** [comment]
@aksld ahhh gotcha. thank you for the follow up, will be on the lookout for any other folks running into the same thing 🙏
