### ISSUE TITLE
Add output method

### ISSUE THREAD

**Issue by mrmadhat** [roots/bud#1595]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

This is a follow on from a question asked here [How to set output folder](https://discourse.roots.io/t/how-to-set-output-folder/23567/2).

I've used Bud through Sage and wanted to use it on another project which required me to set everything up myself. I found it quite difficult to get started because my output directory differed from the default output directory and no additional information was provided about how to do this in the [initial setup guides](https://bud.js.org/guides/getting-started/configure/).

I think the source of my problem was that because the `entry` method exists I assumed that there would be a corresponding `output` method to set the output directory. Even though using setPath seems obvious (and is indeed documented) now that Kelly gave me the answer on discourse I still think adding an `output` method would make life easier for users new to the project.

### Expected Behavior

Add an `output` method that will set the output directory.

### Actual Behavior

-

### Steps To Reproduce

-

### version

latest

### What package manager are you using?

yarn classic

### version

1.22.10

**Comment by kellymears** [comment]
`entry` is a full implementation of the webpack entry api.

so, even though most people will use it like this:

```ts
bud.entry('app', ['app.js'])
```

it's possible to use it like this:

```ts
bud.entry({
  app: {
    import: ['app.js', 'app.css'],
    dependOn: 'react-vendors',
    filename: 'output-filename.js',
  },
  'react-vendors': ['react', 'react-dom', 'prop-types'],
})
```

in contrast, a function named `output` that only set `output.path` is probably not what we want. `output` in webpack [is a massive object](https://webpack.js.org/configuration/output/) and contains many critical options other than the output path.

I do see the need for better documentation, particularly the guides, which are pretty skimpy. But, I don't see a lot of value in having a function named `output` that ultimately just does this:

```ts
function output (path: string) {
  return this.setPath('@dist', path)
}
```

This is also available using a flag: `yarn bud build -o [dir]` or `yarn bud build --output [dir]`

If you (or anybody else) want to update the guide which gave you pause I would gladly review that PR. https://github.com/roots/bud/tree/main/sources/%40repo/docs/content/guides. Otherwise, I'll get around to it as best I can.

Thank you for using bud and sharing your feedback.

**Comment by mrmadhat** [comment]
Hey @kellymears I'll happily update the guide but it'll be next week before I can get round to it.

The cli flag is why I felt that this would be a good addition. IMO it's confusing to have config in two places when users have a need/want to configure bud via a config file and the choices available between the cli and config file differ. Would following the `entry` method be something you would consider? Offering a shorthand to set the output but allowing access to the full `output` object?
