### ISSUE TITLE
[bug] (`@roots/bud-eslint`) `Package subpath './config' is not defined by "exports"`

### ISSUE THREAD

**Issue by strarsis** [roots/bud#1764]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

When using `@roots/bud-eslint` an error is shown when `bud` is invoked (as with builds):
````
Error: Package subpath './config' is not
defined by "exports" in
./node_modules/@roots/bud-eslint/package.json
````

### Expected Behavior

No errors.

### Actual Behavior

An error is shown:
````
Error: Package subpath './config' is not
defined by "exports" in
./node_modules/@roots/bud-eslint/package.json
````

### Steps To Reproduce

1. Create empty Sage 10 theme.
2. Install and setup `bud` `stylelint` support.
3. Invoke `bud` (directly or by running `build`)
Note the error.

### version

6.4.5

### What package manager are you using?

npm

### version

8.19.2

### Logs

```zsh
bud --version
Package subpath './config' is not defined by "exports" in [...]/node_modules/@roots/bud-eslint/package.json
6.4.5
```

### Configuration

```zsh
(No changes to default `bud` configuration were made).
```

### Relevant .budfiles

`.budfiles/bud/profile.json`: (doesn't exist)
`.budfiles/bud/profile.json`: (doesn't exist)

### Relevant configuration files
`.eslintrc.js`:
```cjs
module.exports = {
  root: true,
  extends: [require.resolve('@roots/bud-eslint/config')],
  rules: {},
}
````

The configuration example is probably outdated or incorrect:
https://bud.js.org/extensions/bud-eslint/#:~:text=require.resolve(%27%40roots/bud%2Deslint/config%27)

### Relevant discussions
https://discourse.roots.io/t/eslint-error/23901

Edit: Following this separate documentation page and adding the specific eslint configuration file makes the build work:
https://bud.js.org/extensions/sage/eslint/
This should also be mentioned/linked (related to Sage themes) on the generic `bud-eslint` documentation page.

**Comment by kellymears** [comment]
source: https://github.com/roots/bud/blob/main/sources/%40repo/docs/content/extensions/bud-eslint.mdx

i'll try to get a PR up soon.

thanks @strarsis.

**Comment by strarsis** [comment]
Also another point, not sure whether this was already discussed, but when the lint config files are somehow injected/managed by `bud`, it may be a good idea to let `bud-sass` use `stylelint-config-standard-scss`.

**Comment by kellymears** [comment]
For the eslint docs issue -- I updated the docs in #1761. It moves the doc source into the pkg itself (sources/@roots/bud-eslint/docs/01-configuration.md) so that it is included in the generated `@roots/bud-eslint` readme.

bud doesn't actually manage or manipulate the stylelint config files. It only passes one option on to `StylelintWebpackPlugin` (sets context to the `src` directory). The rest is handled automatically by stylelint. It's pretty hands off. 

https://github.com/roots/bud/blob/9a47120bd74f342993c6bb8337d5f4d189acd653/sources/@roots/bud-stylelint/src/extension.ts#L22

Maybe in the future it could do something similar to `@roots/bud-postcss` and `@roots/bud-babel` and provide an API to manage the base configuration while allowing overrides from a local config. But, right now the above source file is all that bud.js does with stylelint. 

`@roots/bud-sass/stylelint-config` does include the `stylelint-config-standard-scss` as an `extends`. I guess that isn't really exposed in the docs; maybe worth a separate issue.
