### ISSUE TITLE
How to add .scss file support to a sage 10.1.4 installation.

### ISSUE THREAD

**Issue by Leslietoledano** [roots/bud#1877]
Hello! 
Im updating a project created at the beginning of the year with sage 10.1.4 and tailwind 3 (@roots/bud-tailwindcss).

Its using just css files to manage the styles, but now I want to make things cleaner using scss files, more specific the 'import' and "nesting" capabilities to the project.

I navigated trough the roots/bud examples for sage, try adding bud-sass, bud postcss and didnt have any luck.

Here is an example of the last thing I tried (adding it as a postcss plugin): https://discourse.roots.io/t/how-to-add-postcss-plugins-to-bud/21864/7

also here I attach the exact same build I have: https://github.com/roots/sage/releases/tag/v10.1.4

At this point I would love to hear your suggestions if this procedure its sustainable or if I should update everything to the latest versions (expecting lots of migration and compatibility issues too).

**Comment by kellymears** [comment]
@roots/bud-postcss supports nesting and imports.

so all of this syntax just works out-of-the-box:

```css
@import './some/source.css'

.nested {
  .component {
    background: blue;
  }
}
```

that said, i'd recommend trying to keep up with bud.js upgrades. the bud.config.js file in the @roots/sage repo hasn't changed a whole lot in the past year. i don't think it's gonna end up being a ton of work.

any questions about postcss or sass should be covered in the docs:

- https://bud.js.org/extensions/bud-postcss
- https://bud.js.org/extensions/bud-sass

closing this because it's really more suited for discourse than github issues. this is for tracking specific issues with the codebase and the changes made to address them.
