### ISSUE TITLE
[request] Command to only re-build `theme.json` (or no-op)

### ISSUE THREAD

**Issue by strarsis** [roots/bud#2139]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### The feature

A separate `bud` command (or from its `theme.json` extension) that re-generates the `theme.json` 
(or no-op if the `theme.json` generation by `bud` is not enabled).

E.g. something like `bud build theme.json` or `bud build-themejson` maybe?
Or is there already a sub-command or other flag/option that can be used to only build the `theme.json`?

### Use case

The `wp i18n` CLI tool can (and should) also scan the `theme.json` for source translation strings 
(as of colors, font-sizes, template parts, etc.).
When the  `translate:pot` script of Sage theme is invoked, the `theme.json` should first be re-build 
(if generation is enabled, otherwise just no-op), for the `theme.json` to be scanned being up-to-date.
A full rebuild otherwise can be too time consuming and also distracting, 
as only the `theme.json` is (currently) relevant for scanning of translation source strings.

### Notes

Related issue (Sage theme): https://github.com/roots/sage/pull/3076#issuecomment-1442269632

**Comment by kellymears** [comment]
For now, my inclination is to not add complexity and continue to treat it as a build artifact (like `entrypoints.json` or `manifest.json`).

It is relatively easy to add as a bespoke script. Maybe `build-scripts/pre-translate.js`:

```js
import {factory} from '@roots/bud';

const bud = await factory();
await bud.extensions.add(`@roots/bud-wordpress-theme-json`)

//
const {path, ...json} = bud.wpjson.options
await bud.fs.json.write(path, json);
```

Then add it to scripts in `package.json`:

```txt
// ...
"scripts": {
  "translate": "node ./build-scripts/pre-translate.js && wp translate ..."
}
// ...
```

Not super ideal but I think this is a very particular need. Especially if there is js to translate, since that necessitates a build anyway?

Willing to revisit this in the future or entertain follow up. I do think there is something to making it easier to generically script with bud.js. I've tried to make it simple but it's been secondary to the cli since that's how nearly 100% of users interface with it.

**Comment by strarsis** [comment]
Yes, this approach looks good.

Would it make sense to have a `npm` package as `bud` extension that adds a sub-command?

> that necessitates a build anyway?
No, it indeed scans the original JavaScript source files in `resources/`.
