### ISSUE TITLE
[Docs] Explain differences compared to Mix and Encore

### ISSUE THREAD

**Issue by Kilbourne** [roots/bud#84]
Please can you expand which are the differences and the advantages compared ?

**Comment by kellymears** [comment]
my initial attempt at this -- sorry for any inaccuracies.

| feat | mix | encore | bud |
| ---- | ----| ------- | ---- |
| typed |  partial | ❌ | ✅ |
|  mature | ✅ | ✅ | ❌ |
| modular | ❌ | ❌ | ✅ |
| multi-compiler | ❌ | ✅ | ✅ |
| ts config | ❌ | ❌ | ✅ |
| yml config | ❌ | ❌ | ✅ |
| js config | ✅ | ✅ | ✅ |
| json config | ❌ |❌ | ✅ |
| zero config | ❌ |❌ | ✅ |
| compatible with webpack cli | ❌ | ✅ | ✅ |
| persistent cache | ❌ |❌ | ✅ |
| babel support | ✅ |✅ | ✅ |
| react support | ✅ |✅ | ✅ |
| vue support | ✅ |✅ | ✅ |
| sass support | ✅ |✅ | ✅ |
| postcss support | ✅ |✅ | ✅ |
| stylus support | ✅ |✅ | ❌ |
| typescript support | ✅ |✅ | ✅ |
| less support | ✅ |✅ | ❌ |
| emotion support | ❌ |❌ | ✅ |
| md support | ❌ |❌ | ✅ |
| mdx support | ❌ |❌ | ✅ |
| esbuild support | ❌ |❌ | ✅ |
| loader config api | ❌ | ✅ | ✅ |
| rule config api | ❌ | ✅ | ✅ |
| plugin config api | ❌ | ✅ | ✅ |
| wordpress specific support | ❌ |❌ | ✅ |
| laravel specific support | ✅ | ❌ | ❌ |
| symfony specific support | ❌ | ✅ | ❌ |
| dependency management cli tooling | ❌ | ❌ | ✅ |

- I am only counting features supported by _first-party_ maintained packages. For example, I have written a plugin to add emotion support to mix, but I don't think that's as reliable as mix shipping with it. Likewise, I am not keen to ever be in a position where I am supporting less (since I don't use it), so that's  not counted as a bud feature. But it is worth noting that many of these features (really everything except vanilla js/css) must be _installed_ with bud. Bud does not even ship with support for babel.
- By "modular" I mean that core components can be replaced or re-implemented, and there are strict contracts in place to guarantee interoperability in those cases. With `bud` you can extend or replace core components prior to instantiating the framework -- with encore and mix you can override components at runtime but that isn't really the same. 
- Mix is a js project that provides type definition files, bud is a typescript project, and encore is purely js (although they use jsdoc comments). This matters for intellisense quality.
- Encore and Mix probably have better support for vue than bud does. Bud only supports single file components, for instance,  and does not support vue as a runtime dep. I believe this is an option with both Mix and Encore. I think bud generally has better support React than mix or encore, on the other hand (I don't think either explicitly supports react-refresh, for instance). 
- Bud has _hundreds_ of hooks available for users to tap into to customize different parts of their configs. I think Mix has two (`before` and `after`). Encore, to my knowledge, doesn't use keyed hooks at all. Merging a webpack config is a very different developer experience to using a hook to manipulate a value ad-hoc.
- Mix and Encore both support applications outside of PHP, but I don't think either of them do things like generate html boilerplate. Bud allows you to generate a fully production ready project purely with JS.

**Comment by kellymears** [comment]
[🎉 This is done](https://bud.js.org/guides/overview/what-is-bud)
